CREATE DATABASE IF NOT EXISTS cnube DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'usuario'@'%' IDENTIFIED BY 'usuariopassword';
GRANT ALL PRIVILEGES ON cnube.* TO 'usuario'@'%';
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS usuario (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    eMail VARCHAR(255) NOT NULL,
    pwd_ VARCHAR(255) NOT NULL,
    fecha DATE NOT NULL,
    nombre VARCHAR(100),
    estatus VARCHAR(1) NOT NULL
)

